# Generated by Django 3.2.6 on 2021-09-20 08:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('course', models.CharField(blank=True, max_length=50, null=True, verbose_name='Курс')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Посмотрено')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
        migrations.CreateModel(
            name='EmailSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'EmailSubscribe',
                'verbose_name_plural': 'EmailSubscribe',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, max_length=50, null=True, verbose_name='Родитель')),
                ('parent_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Родитель (англ)')),
                ('parent_image', models.ImageField(blank=True, upload_to='images/', verbose_name='Родитель аватар')),
                ('parent_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='Родитель описание')),
                ('parent_info_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Родитель описание (англ)')),
                ('kid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ребенок')),
                ('kid_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ребенок (англ)')),
                ('kid_image', models.ImageField(blank=True, upload_to='images/', verbose_name='Ребенок аватар')),
                ('kid_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ребенок описание')),
                ('kid_info_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ребенок описание (англ)')),
                ('parent_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Родитель текст')),
                ('parent_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Родитель текст (англ)')),
                ('kid_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ребенок текст )')),
                ('kid_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ребенок текст (англ)')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_page_img', models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка примеры занятий')),
            ],
        ),
        migrations.CreateModel(
            name='TariffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название (рус)')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название (англ)')),
            ],
            options={
                'verbose_name': 'Категория тарифа',
                'verbose_name_plural': 'Категории тарифа',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='teacher/images/', verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО (англ)')),
                ('lang', models.CharField(blank=True, max_length=50, null=True, verbose_name='Язык')),
                ('lang_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Язык (англ)')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст (англ)')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название (англ)')),
                ('info', models.CharField(blank=True, max_length=50, null=True, verbose_name='Доп. информация')),
                ('info_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Доп. информация (англ)')),
                ('price_rub', models.IntegerField(default=0, verbose_name='Стомость Р')),
                ('price_usd', models.IntegerField(default=0, verbose_name='Стомость $')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка %')),
                ('lessons_count', models.IntegerField(default=0, verbose_name='Кол-во занятий')),
                ('is_personal', models.BooleanField(default=False, verbose_name='Индивидуальный?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs', to='data.tariffcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
