# Generated by Django 3.2.6 on 2021-09-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название уровня (рус)')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название уровня (англ)')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название типа занятия (рус)')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название типа занятия (англ)')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятия',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='group/logo', verbose_name='Логотип группы')),
                ('label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название группы')),
                ('login', models.CharField(blank=True, max_length=50, null=True, verbose_name='Логин для ZOOM / WebEx')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пароль для ZOOM / WebEx')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.grouplevel', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
