# Generated by Django 3.2.6 on 2021-09-20 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.grouptype', verbose_name='Тип занятия'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='ДЛЯ ДОБАВЛЕНИЯ ИЛИ УДАЛЕНИЯ УЧЕНИКА К ЧАТУ ГРУППЫ, ГРУППУ НУЖНО СОХРАНИТЬ 2 РАЗА', null=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
    ]
