# Generated by Django 3.2.6 on 2021-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='link',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Ссылка по умолчанию для всех уроков группы'),
        ),
    ]
