# Generated by Django 3.2.6 on 2021-09-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNewMessages', models.BooleanField(default=False, verbose_name='Есть новые сообщения')),
                ('lastMessageOwn', models.BooleanField(default=False)),
                ('is_stream_chat', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/', verbose_name='Файл к сообщению')),
                ('isUnread', models.BooleanField(default=True, verbose_name='Не прочитанное сообщение')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='В чате')),
            ],
        ),
    ]
