# Generated by Django 3.2.6 on 2021-09-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='personal/files/', verbose_name='Файл')),
                ('is_single', models.BooleanField(default=False)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True, verbose_name='Название папки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тема урока')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('old_date', models.DateField(blank=True, null=True, verbose_name='Предыдущая дата урока')),
                ('old_time', models.TimeField(blank=True, null=True, verbose_name='Предыдущее время урока')),
                ('link', models.TextField(blank=True, max_length=50, null=True, verbose_name='Ссылка')),
                ('is_has_new_datetime', models.BooleanField(default=False, verbose_name='Урок перенесен ?')),
                ('is_over', models.BooleanField(default=False, verbose_name='Урок завершен ?')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('is_over', 'date', 'time'),
            },
        ),
        migrations.CreateModel(
            name='UploadedMaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson/material/files/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_uploaded', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_material', to='lesson.lesson', verbose_name='Загруженный файл')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedHomeWorkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson/homework/files/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_uploaded', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_homework', to='lesson.lesson', verbose_name='Загруженный файл')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='present', to='lesson.lesson', verbose_name='Урок')),
            ],
        ),
    ]
