# Generated by Django 3.2.6 on 2021-10-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_lesson_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
