# Generated by Django 3.2.6 on 2021-10-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_lesson_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
    ]
