# Generated by Django 3.2.6 on 2022-02-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_alter_lesson_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='timeoffset',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Смещение'),
        ),
    ]
