# Generated by Django 3.2.6 on 2021-10-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
