# Generated by Django 3.2.6 on 2021-11-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211025_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_marked',
            field=models.BooleanField(default=False, verbose_name='Особая отметка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user', verbose_name='Фото'),
        ),
    ]
