# Generated by Django 3.2.6 on 2021-11-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_payment_free_lessons_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='free_lessons_count',
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
