# Generated by Django 3.2.6 on 2021-11-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211125_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='promo_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Использованный промо-код'),
        ),
    ]
