# Generated by Django 3.2.6 on 2021-12-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211216_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotification',
            old_name='is_notify',
            new_name='is_reward',
        ),
    ]
