# Generated by Django 3.2.6 on 2022-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_reward_is_full_cource_reward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ('-is_new', '-created_at')},
        ),
        migrations.AddField(
            model_name='userreward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
