# Generated by Django 3.2.6 on 2022-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20220125_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreward',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
