# Generated by Django 3.2.6 on 2022-01-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_userreward_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название англ'),
        ),
    ]
