# Generated by Django 3.2.6 on 2022-01-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_reward_label_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreward',
            name='created_at',
        ),
    ]
