# Generated by Django 3.2.6 on 2022-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_usedpromocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='orderNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_pal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
